### ISSUE TITLE
Index.yaml location

### ISSUE THREAD

**Issue by mitchhentges** [GoogleCloudPlatform/google-cloud-java#1334]
I'm running my application as a Jetty jar: `java -jar app.jar` will start a webserver on `$PORT`, which serves both static files and services API calls.

I'm having an issue with datastore indices not being honoured. I've followed the instructions both on [`google-cloud-java`](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-datastore#running-a-query) and its linked [datastore-index-specific page](https://cloud.google.com/datastore/docs/tools/indexconfig), which appears to state that the index configuration `index.yaml` should be in `WEB-INF/index.yaml` in my jar:

> The index.yaml is located in the <project-directory>/WEB-INF/ folder.

However, even with this `index.yaml` file configured, my datastore requests are still failing:
```
Caused by: com.google.datastore.v1.client.DatastoreException: no matching index found. recommended index is:
- kind: TextMessage
  properties:
  - name: sender
  - name: date
```

Is my `index.yaml` in the correct spot? Can I provide the `index.yaml` resource path to the Client Datastore API? Is the `index.yaml` supposed to be visible on my app via an `http` request?

For reference, my `index.yaml` is:
```
indexes:
- kind: TextMessage
  properties:
  - name: sender
  - name: date
```

**Comment by mitchhentges** [comment]
Note: I've investigated the Bookshelf example (all other links are broken on http://googlecloudplatform.github.io/google-cloud-java/0.4.0/index.html), and it has an [`index.yaml`](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf/4-auth/index.yaml). However, after building a Bookshelf `war` file, it doesn't have an `index.yaml` in it?

**Comment by mziccard** [comment]
Hi @mitchhentges!

The creation of indexes from a local file (`index.yaml`) is not done by our library. When you deploy an App Engine app, `index.yaml` is used to update/create indexes in datastore as part of the deploy process.

Since it does not seem you are deploying your application to AppEngine, the `gcloud` command comes to the rescue and allows you to set indexes for Datastore given a `index.yaml` file. Use the `google preview datastore create-indexes` command (docs [here](https://cloud.google.com/sdk/gcloud/reference/preview/datastore/create-indexes)) to create index in the production Datastore from a local `index.yaml`.

[Here](https://cloud.google.com/datastore/docs/tools/#the_development_workflow_using_gcloud) you can find an interesting example of development workflow when using Datastore.

**Comment by mitchhentges** [comment]
Sweet, thanks!
