### ISSUE TITLE
netty 4.1.3 memory leak affecting pubsub

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-java#1433]
We believe the following issue https://github.com/grpc/grpc-java/issues/2358 is affecting the pubsub as we are seeing OOM exceptions.

As gcloud 0.5.0 and 0.7.0 java is hard bundled with GRPC & netty version 4.1.3 it won't work by overriding the netty-all version (reason unknown but it is just quiet...)

Would it be possible to upgrade this dependency or let us know how this dependency can be manually overridden?

**Comment by garrettjonesgoogle** [comment]
Try using the exclusions feature of Maven in the short term:

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

You would add this exclusions section to your dependency declaration on `google-cloud-java`, and then add a direct dependency on the Netty version that you want.

Let me know if this works for you.

We'll try to get it fixed in `google-cloud-java` too, but that will take a little bit longer.

**Comment by fonzy2013** [comment]
thanks! We will try it out right away

**Comment by fonzy2013** [comment]
We didn't see a huge difference with exclusion or not as 4.1.6.Final with exclusion showed the same silent results.
We did however get 4.1.5 to work. We'll keep you posted.

**Comment by msufa** [comment]
After implementing the suggested workaround and falling back to `netty 4.1.5` our heap usage decreased dramatically for pubsub & gcs operations:

![heap_usage](https://cloud.githubusercontent.com/assets/4570601/20932868/6c58eb2a-bbd6-11e6-9dad-1a805e29d9da.png)

The fix was deployed on Nov 30th as you can see from the graph.

When using `netty 4.1.6` with `google-cloud 0.5.1` we did not see any executor threads getting created. Downgrading `netty` seems to have done the trick.

We're looking forward to seeing the latest `netty` being used in the next release! 😃

**Comment by garrettjonesgoogle** [comment]
Hi,

In the latest release (`0.8.1-alpha`) the transitive netty dependency is now `4.1.6.Final`. I was unclear from this thread if 4.1.6 causes problems - could someone verify?

**Comment by fonzy2013** [comment]
@garrettjonesgoogle we haven't tested with 4.1.6 as we are happy with the results on 4.1.5 at the moment.

**Comment by garrettjonesgoogle** [comment]
I will resolve this now. Open a new issue (and link to this one) if the issue comes up in a different version of Netty.
