### ISSUE TITLE
Publisher javadocs example fails to compile

### ISSUE THREAD

**Issue by JaysonRaymond** [GoogleCloudPlatform/google-cloud-java#1652]
From http://googlecloudplatform.github.io/google-cloud-java/0.9.2/apidocs/com/google/cloud/pubsub/spi/v1/Publisher.html

(Checked both  0.9.0-alpha or 0.9.2-alpha):

:
  List<RpcFuture<String>> results = new ArrayList<>();
:
  Futures.addCallback(
  Futures.allAsList(results),
 :
 
Futures.allAsList & Futures.addCallback both require a ListenableFuture, not an RpcFuture.
 
The Rpc implementation is coming from Gax-0.1.0.

**Comment by pongad** [comment]
@JaysonRaymond This is a miss from my side. I neglected to update the sample at the time.

This was fixed in [0.9.3](http://googlecloudplatform.github.io/google-cloud-java/0.9.3/apidocs/com/google/cloud/pubsub/spi/v1/Publisher.html).

I'll close this for now; please reopen if you have any more concerns.
