### ISSUE TITLE
Enable PubSubHelper to work with new APIs

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/google-cloud-java#1777]
The PubSubHelper class has moved to the `deprecated` package. Currently when trying to use it and configure a PublisherClient, I'm getting exceptions with authentication and refrershtoken not being supported on NoCredentials class provided by the PubSubHelper. 

Even after configuring that, the server throws errors on calls not being in HTTP/2 format.

It would be great if we could user the PubSubHelper to make self contained integration tests that do not rely on the cli emulator or the platform.

**Comment by garrettjonesgoogle** [comment]
`PubSubHelper` has been deleted completely since this issue was filed. The recommended way to use the Pub/Sub emulator is documented at https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-pubsub .

I'm going to close out this issue now - feel free to contact us again if you have more concerns.
