### ISSUE TITLE
Shade Guava in google-cloud-spanner

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#1802]
Spanner.closeAsync() exposes ListenableFuture from Guava

Causing issues when writing a POC w/ @emmanuelbernard on Hibernate OGM dialect.

**Comment by garrettjonesgoogle** [comment]
This should be switched to ApiFuture from GAX.

**Comment by vkedia** [comment]
@garrettjonesgoogle I started looking into this. There does not seem to be any way to convert a ListenableFuture to ApiFuture. In absense of that change becomes more involved since this future internally waits on completion of a list of ListenableFutures for which I am using Futures.allAsList but there is no such method for ApiFutures.
Do you think it makes sense to expose a method in gax that converts a ListenableFuture to ApiFuture? It does seem to exist internally:
https://github.com/googleapis/gax-java/blob/master/src/main/java/com/google/api/gax/core/internal/ApiFutureToListenableFuture.java

**Comment by vkedia** [comment]
Sent your a PR to add allAsList to ApiFutures
https://github.com/googleapis/gax-java/pull/267

**Comment by garrettjonesgoogle** [comment]
If gax exposed a method that converted a `ListenableFuture` to `ApiFuture`, the whole point of creating `ApiFuture` to wrap `ListenableFuture` would be defeated. I think adding `allAsList` to `ApiFutures` is the right way to go.

**Comment by vkedia** [comment]
I believe this is done. Though I also sent a #2026 which removes the need for future completely by making close a blocking call.

**Comment by vkedia** [comment]
Closed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1960
