### ISSUE TITLE
Spanner - consider adding .set(...).toNull() method

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#1804]
Currently setting a field to null requires to call the type-specific `.to(...)` method for the type. If setting something to null, we need to `.set("field").to((String) null)`

Consider adding a `.set(...).toNull()` method

**Comment by saturnism** [comment]
ping @vkedia - this would be really useful. :)

**Comment by vkedia** [comment]
@saturnism I agree this would be useful. But the problem is, the way Value class is designed currently, it needs to know the type of value. So this is not as straightforward as I had initially thought. I am trying think about how to best support this. Would a method like `toNull(Type type)` be useful?

**Comment by emmanuelbernard** [comment]
@vkedia hello. I think my main pain point was to guess the type, not to call `to(null)`. So I don't think your proposal `toNull(Type type)` really solves the core problem.
But if you really really cannot guess the type on your end and absolutely need one, then your method proposal is at least more generic than the down casting in `.to((String) null)`.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
