### ISSUE TITLE
PubSub - doesn't work on App Engine Standard

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-java#1807]
Since the pubsub client lib is all async and uses thread pools (which GAE Standard doesn't allow), the pubsub lib doesn't work on GAE Standard.

**Comment by garrettjonesgoogle** [comment]
Could you make a request for a specific change you would like to see?

**Comment by jerjou** [comment]
At a high level, I'd like our client libraries to work on GAE Standard :-) I can think of a couple options I'd be happy with:

* GAE Standard supports background threads making urlfetches (this should fix at least the problem I'm currently encountering, when trying to publish to a topic on GAE Standard). I understand this option is outside the scope of this repo :-)
* PubSub client lib otherwise gets its background threads' urlfetches working on GAE Standard (perhaps by using [ThreadManager](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/ThreadManager)?)
* PubSub client lib exposes synchronous versions of its methods, so GAE Standard users can make calls on the main thread

**Comment by briangranatir** [comment]
You probably already know this, but this is the error that appears when trying to run the new PubSub lib on GAE Standard (I'm using Java):

> Google App Engine does not support Runtime.addShutdownHook

Would be nice if the new Cloud Client Libraries all worked on GAE Standard

**Comment by garrettjonesgoogle** [comment]
Development since this issue was filed: Java 8 on App Engine Standard will support gRPC, so Pub/Sub should work in that environment. Unfortunately, it won't work on Java 7 and there are no plans to support that. The work to get open issues fixed for Java 8 on App Engine Standard is being tracked in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1918 . I am going to close out the present issue - follow along in #1918 for progress.
