### ISSUE TITLE
ResultSet should implement Iterable.

### ISSUE THREAD

**Issue by buchgr** [GoogleCloudPlatform/google-cloud-java#1816]
It seems convenient for `com.google.cloud.spanner.ResultSet` to implement `Iterable` or `Iterator`. It would allow for easier use with existing Java/JDK APIs. Right now, I have to roll my own Iterator :(.

**Comment by vkedia** [comment]
@buchgr Spanner ResultSet has been designed to look like java.sql.ResultSet which does not implement an iterator as well. Also note that there is a bit of api mismatch between ResultSet and Iterator due to next() in ResultSet being similar to hasNext() in iterator. Also the pattern we want to encourage it for users to directly call accessors like getString on ResultSet since they are more efficient then getting a Struct and then calling accessors on that.
