### ISSUE TITLE
Should we use  javax.annotation.Nullable and javax.annotation.concurrent.Immutable

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#182]
Part of JSR-305.

These annotations are part of Java 8, but could be used before by including this dependency

```
<groupId>com.google.code.findbugs</groupId>
<artifactId>jsr305</artifactId>
```

**Comment by eamonnmcmanus** [comment]
Actually the annotations are not part of Java 8, which is good because you can include them from the jsr305 jar and it will work the same everywhere. What changes in Java 8 is that you have type annotations, so you can write things like `List<@Nullable String>`. Conversely, you can't write that if you want to compile on earlier versions, though you can still write `@Nullable String frob(@Nullable String s)`.

`@Nullable` in particular can provide a useful service to client code if that code is using FindBugs or another similar tool.

**Comment by garrettjonesgoogle** [comment]
Stale issue, closing out.
