### ISSUE TITLE
GAPIC clients: merge service address and port

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1835]
It's natural for service address and port to go together - for example, environment variables for emulator hosts from the gcloud command (e.g. `PUBSUB_EMULATOR_HOST`) includes service address and port in a single value. We should just merge these together to make life easier on everyone. 

I'm unsure if this is beta blocking, but I'll proactively mark it as such until further discussion.

**Comment by garrettjonesgoogle** [comment]
We have pulled in the version of gax that provides setEndpoint, so it seems like we can close this now.

**Comment by pongad** [comment]
@garrettjonesgoogle I started looking into this issue and have a question. Looking at [this line](https://github.com/googleapis/toolkit/blob/8cbb2817facb641b8987d570ff040bf700c8899a/src/main/resources/com/google/api/codegen/java/settings.snip#L144), it looks like we sometimes don't have the default  address but we have the default port.

- Is this intended behavior? If we don't know which host to connect to, how do we know what port to connect?
- If it is the intended behavior, does this mean we need to leave the `setPort` un-deprecated?

**Comment by garrettjonesgoogle** [comment]
Across the board, default port is probably going to be the same (443) for the "real" services. I don't think we need `setPort` un-deprecated; I think we just need to default it in gax itself.

**Comment by pongad** [comment]
From what I can see, the only place where `setPort` is used in isolation is LRO, because the client by itself doesn't know what service to connect to. However, clients who use LRO just sets the channel provider, not the address and port.

So, if there is no default address, then the port can also be removed without any ill effects. I'll do this for now, but please let me know if you want it added back.
