### ISSUE TITLE
Integration Tests with Emulators

### ISSUE THREAD

**Issue by fkorotkov** [GoogleCloudPlatform/google-cloud-java#2024]
[Testcontainers project](https://github.com/testcontainers/testcontainers-java) allows to use services running in containers to be used during testing. It will be great to add such tests for available emulators using [google/cloud-sdk](https://hub.docker.com/r/google/cloud-sdk/) container.

I have a proof of concept [here](https://github.com/fkorotkov/snippets/tree/master/testcontainers/gcloud) that shows how to run such tests in Travis.

If this idea look good to everyone I can try to add some simple tests after https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1973 is fixed.

**Comment by shinfan** [comment]
I don't think google-cloud-java contains any source code of gcloud emulators.

**Comment by fkorotkov** [comment]
Right, @shinfan. But wouldn't it be great to verify `google-cloud-java` works properly with emulators to catch problems like #1973?

**Comment by shinfan** [comment]
Oh I sorry I misunderstood. I think it makes sense to make sure gcloud work with emulators.

**Comment by garrettjonesgoogle** [comment]
It's not clear what this request is for currently. Our current stance is for users of google-cloud-java to start emulators themselves, and then customize the API clients in google-cloud-java to use the running emulator instead of the real service. What else is needed?

**Comment by fkorotkov** [comment]
The problem I've seen before that `google-cloud-java` stopped working with emulators. It will be nice to make sure changes to `google-cloud-java` are not breaking it ability to talk to emulators.

**Comment by fkorotkov** [comment]
It might be fine to not have them since `google-cloud-java` is getting more and more stable. 🤷‍♂️

**Comment by garrettjonesgoogle** [comment]
We intend on continuing to support the special functionality necessary for emulators (plain text, no credentials). With that, I don't think emulators would generally break. It's a challenge to verify emulators in google-cloud-java because that requires extra dependencies that are problematic (either the python-based gcloud utility, or downloading the emulator from the internet). I think I'll close this out - feel free to open a new issue if emulators break in the future.
