### ISSUE TITLE
Can't specify the encodingType at all on AnalyzeSentiment method of LanguageServiceClient

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#2076]
The issue in question was filed in googleapis/googleapis repo since it's a config bug. But creating a new issue here for better visibility since Java is probably the most affected by this bug.

Root issue with details: https://github.com/googleapis/googleapis/issues/348

**Comment by saturnism** [comment]
encountered this issue myself

**Comment by garrettjonesgoogle** [comment]
It turns out that `encoding_type` affects offsets in the output, but AnalyzeSentiment currently doesn't populate any offsets in the response. So while this is obviously a gap, it doesn't mean that any functionality is actually impeded. Consequently, downgrading to P2+. 

We can keep discussing the automated logic necessary to populate `encodingType` in googleapis/googleapis#348 .

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
