### ISSUE TITLE
Make specifying project ID optional for PubSub Topic

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-java#2094]
Currently, creating a topic requires knowing the project ID. However, the client libraries have a way of automatically [figuring out what the project ID is based on the environment](https://github.com/GoogleCloudPlatform/google-cloud-java#specifying-a-project-id). It should fall back to that if project ID is not specified.

**Comment by garrettjonesgoogle** [comment]
Our current recommendation is for users to call `ServiceOptions.getDefaultProjectId()` and pass that in.

There is a circular problem with having generated code depend on types in google-cloud-java, so we have decided not to make this automatic for the time being.

**Comment by yasikmondal** [comment]
garrettjonesgoogle Do you have any java tutorial link where it's explain this object change notification with code?

**Comment by garrettjonesgoogle** [comment]
@yasikmondal , could you elaborate? I don't quite understand.

**Comment by yasikmondal** [comment]
@garrettjonesgoogle  - I have created a servlet project to do image transform on google app engine. I will take the image from cloud bucket and will convert and will store it back to the another cloud bucket. Now I want to do it automatically like if anyone is updating or changing any object to any cloud bucket, our application should automatically get triggered (object change notification) and should do all those stuff (conversion).

Now I need to implement this feature object change notification as I am running my application on cloud app engine.

Do you have any demo or tutorial in java so that I can check.

**Comment by garrettjonesgoogle** [comment]
@yasikmondal your request seems to be unrelated to the present issue. I recommend filing an issue at https://github.com/GoogleCloudPlatform/java-docs-samples . Thanks!

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
