### ISSUE TITLE
When will this not be seen :)

### ISSUE THREAD

**Issue by XinyueZ** [GoogleCloudPlatform/google-cloud-java#2140]
I see this always, however, as Android Dev, I wanna use this library for the future to instead [this](https://developers.google.com/api-client-library) .
> Does it work on Android?
Android is currently unsupported.

**Comment by garrettjonesgoogle** [comment]
We don't have a specific timeline. So far, the supported services are meant to be used from other services (because they use service account credentials), not on Android (where it's safer to use user credentials). When we start adding support for services that are meant to be used on Android, we will definitely work through the Android compatibility issues.

I'm going to close this out now - feel free to open if you want to follow up.
