### ISSUE TITLE
Throw more granular exception on ImageAnnotatorClient.close()

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-java#2216]
Currently, the image annotator client can throw the generic "Exception" on close. I found this while making [the update to close the image annotator client](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/746) in the vision sample.

**Comment by michaelbausor** [comment]
I think this may be unavoidable, because the `AutoCloseable` interface throws `Exception`: https://docs.oracle.com/javase/7/docs/api/java/lang/AutoCloseable.html#close()

**Comment by michaelbausor** [comment]
Relevant code in image annotator client: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorClient.java#L232

**Comment by gguuss** [comment]
I see, it sounds like they "strongly encourage implementations to throw more specific exceptions" but it's not clear how they expect you to implement this.

**Comment by michaelbausor** [comment]
Yes, it isn't clear what we could do. One possibility would be to use a list of `Closeable` instead of `Autocloseable`. But I would be worried that at some future point, we would want to add an `Autocloseable` and need to change it back.

I am closing this for now, but if you want to discuss possibly switching to `Closeable` or some other option, please reopen!
