### ISSUE TITLE
Setting the Flow Control MaxOutstandingElementCount cause stuck messages

### ISSUE THREAD

**Issue by robertsaxby** [GoogleCloudPlatform/google-cloud-java#2452]
The behaviour was observed in the 0.21.1-beta version of the Java client library
It seems resolved in the 0.23.1-beta version, however this newer version implements the bi-directional streaming pull and the previous doesn't.

**Test Setup:**
- 100k messages published to a Topic
- Single Subscription
- _n_ Subscribers (k8s running on GKE, each pod running in separate node) {_n_ ∈ Z |  1 ≤ _n_ ≤ 4}
- Each node had 2 vCPU and each Subscriber provided 10 user threads to the client library
- All Subscribers running the same code (Parse message, build various classes, callback processing takes ~20ms)
- Flow control settings: MaxOutstandingElementCount: 1000
**Results:**
- _n_ Messages remain stuck on Topic _n_  ∈ [223, 6652]
**Observations:**
- When messages are stuck: mod_ack_deadline_request_count  > 0, Pull request count > 0
- When messages are stuck Subscriber callback threads are Waiting
- No stuck messages when retesting with default Flow Control Settings (i.e. MaxOutstandingElementCount = null)
- Experiments with MaxOutstandingElementCount ∈ [1000, 500, 250, 125] resulted in stuck message count ∈ [~6K, ~3K, ~1.7K, ~6K]

**Interpretation:**
Message ACK deadlines are being continuously extended and the callback threads are not being invoked

**Comment by kir-titievsky** [comment]
@robertsaxby It sounds like the subscriber application code executes the listener MessageReceiver (parsing the message, etc), but never calls AckReplyConsumer.ack for some messages.  Can you confirm that:
* The MessageReceiver implementation actually calls AckReplyConsumer.ack explicitly in the user code.
* That for stuck messages the listener code executes successfully, including a call to .ack?

**Comment by kir-titievsky** [comment]
Got answers offline: The call to .ack happens successfully in the application code, but the acks are never actually sent.

**Comment by pongad** [comment]
I'll look into this, but @robertsaxby is there any reason you cannot move to streaming pull?

**Comment by pongad** [comment]
Good news is I can reproduce this. I'm working to determine the root cause.

**Comment by pongad** [comment]
I found the problem. @davidtorres @mdietz94

The bug is actually in [`MessageDispatcher::processOutstandingBatches`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/91ad4f465ed5cbd2f7853290a33555b00e5c9aed/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java#L355). The method works roughly like this:

1. We keep a queue of messages we pulled but haven't processed (outstandingMessageBatches)
2. We pull one message, and try to reserve a spot for it. If there's no spot left, do nothing, and the message stays in the queue.
3. If we get a spot, process the message.
4. After processing, call the method again.
The idea is that if the flow control is full, then there's at least one message executing. When we finish, it will cause us to process more.

The problem is that we have many MessageDispatchers but only one FlowController. Consider a scenario where the flow controller has room for 1 message, but we have dispatchers, A and B.

- A and B pulls 1 message each
- A gets the spot
  - This means B stops at step 2 above
- A executes its message
- When the message finishes, A looks for more work *in its own queue* and doesn't realize B has a message. B's message will sit in the queue forever. Of course, B dutifully extends the message's deadline.

This explains @robertsaxby 's observations (I split out the points a little differently)
- n Messages remain stuck on Topic
  - those messages are in B's queue
- When messages are stuck: mod_ack_deadline_request_count > 0
  - B is extending the deadlines
- When messages are stuck: Pull request count > 0
  - B is stuck, but A isn't; the pulls are probably coming from A
- No stuck messages when retesting with default Flow Control Settings (i.e. MaxOutstandingElementCount = null)
  - because in step 2 there's always a spot left, so we always reach step 3.

I see two ways out of this:
1. Make all dispatchers share the same queue.
This will probably increase contention. I have an idea that might reduce it.
2. Give every dispatcher its own control flow (where each has `totalSlots/numDispatchers` slots).

David and Max, do you have a preference? I'm leaning towards 1.

**Comment by kir-titievsky** [comment]
@pongad : The reason @robertsaxby went back to the original library was to work around the idle streams issue.

**Comment by mdietz94** [comment]
I agree with 1, I think each having its own control flow will lead to poor flow control behavior if the dispatchers do not fill fairly.

**Comment by davidtorres** [comment]
Also agree with 1

David Torres | Senior Software Engineer | davidtorres@google.com | +1
212-565-9096
