### ISSUE TITLE
Dependency Errors While Using Maven shade jar

### ISSUE THREAD

**Issue by TheSkripterDK** [GoogleCloudPlatform/google-cloud-java#2491]
Okay so I use maven shade jar here is my pom.xml https://pastebin.com/6rASfHss

but I get these errors https://pastebin.com/xpTDApiL
I compile using clean package
have done a google search and it looks like it has something to do with guava

**Comment by garrettjonesgoogle** [comment]
What is the reason you decided to file the issue against google-cloud-java?

**Comment by btilford** [comment]
I believe it's the way google-cloud-java depends on guava. It makes it unusable with other libraries that depend on a different version of guava. _(google libraries depend on it heavily for example)_. Lot's of APIs being added/removed things that are `@Beta` being used etc.

Really the only way to fix it is repackaging google-cloud-java libs with a shaded guava yourself then pulling that in instead of the real libraries.

An example of a bad mix of guava would be having a project that used 
* Google api client, GA for example
* BigQuery client
* Dataproc (Hadoop, Spark) with BigQuery connector

**Comment by pongad** [comment]
@garrettjonesgoogle Since we're already shading netty, is there anything stopping us from shading guava too?

**Comment by garrettjonesgoogle** [comment]
gRPC is the layer shading netty, not google-cloud-java. We would need separate shading work to shade guava in google-cloud-java.

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
