### ISSUE TITLE
Pub/Sub StreamingSubscriberConnection  : Terminated streaming with exception

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-java#2506]
See related issue on the spring-cloud-gcp project at https://github.com/spring-guides/gs-messaging-gcp-pubsub/issues/4.

**Comment by pongad** [comment]
Good timing :smile: ! I just submitted this [PR](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2492) to solve the problem.

The pubsub server sometimes terminate the stream proactively. We catch this, sleep a bit (just in case the server is heavily loaded), and reconnect. This is OK, but we log it at high severity which makes the log looks scary. The linked PR lowers the severity in cases where we can reconnect. Bad errors like "subscription doesn't exist" still gets logged at SEVERE.

Since the PR is merged and will go out in the next release, I'll close this issue. Please reopen if you need anything else!

**Comment by meltsufin** [comment]
@pongad I'm not sure if the PR fixes it though. The OP was saying that they stop receiving messages altogether. So, it's not just a logging issue as far as I understand.

**Comment by pongad** [comment]
@meltsufin Ah I'm sorry I misread.

There are two known issues that might have caused this.

The first suspect: We exponentially back off but previously did not cap the reconnect time. So we'd reconnect eventually but after a long long long time after a while. This was fixed by [this PR](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2409/) and should have gone out in v0.23.0. Do you already have this version?

The second suspect: After the stream goes idle for a little while, there's a problem where a firewall might close the stream without notifying us so we wait for the messages that will never come. The "right thing to do" here is to configure a keep alive in gRPC, but this needs to wait for next gRPC release. In the meantime, could you try running this command? (assuming you're Linux):
```
sudo /sbin/sysctl -w net.ipv4.tcp_keepalive_time=60 net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5
```
This should get the kernel to do the keepalive for us.

**Comment by meltsufin** [comment]
We're on `0.24.0-beta`. So, I think it might be the second suspect.
Since the application is containerized, do you suggest adding that line to the `Dockerfile`?

**Comment by pongad** [comment]
I think it should be OK to add the command to fix the immediate problem.

For the longer term fix, gRPC just released 1.7.0 which contains the new feature we need. I've just created [PR](https://github.com/googleapis/gax-java/pull/382) to update the dependency; the master branch should get the fix in a few days. (I'm in Australia, so code review latency is a little high.) After this change is released, you shouldn't need to run that command anymore.

**Comment by rajithavk** [comment]
@pongad `sudo /sbin/sysctl -w net.ipv4.tcp_keepalive_time=60 net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5` this may not work for Docker containers, it was said somewhere that docker restricts certain kernel parameter tuning for security reasons. At least the options were not avaialble under /proc/sys/net/ipv4/ for the images I checked.

**Comment by pongad** [comment]
OK, we'll prioritize gRPC 1.7. @garrettjonesgoogle Is there anything blocking us from releasing new gax? I can pick this up if Seattle folks are busy.

**Comment by garrettjonesgoogle** [comment]
There's nothing blocking us.

**Comment by jkupcho** [comment]
Semi related question.  

I've been receiving similar error messages, but within the Spring Framework.  I'm wiring a Subscriber as a singleton with `startAsync` as the `initMethod`, and `stopAysnc` as the `destroyMethod`.  I can't seem to find anything in the documentation that says Subscribers can be treated as thread-safe, but it seems like async pull subscribers should be long lived.

Should these be managed outside the Spring Framework through some sort of Factory?

**Comment by Mistic92** [comment]
I have problem with not receiving messages singe 0.19 or something like this. After ~10-15min it's stopping receiving messages. Currently I'm "restarting" subscribers every 5min by stopAsync() and just creating it again. I didn't found any other way :( 
I had created healthcheck to monitor subscriber and apiservice but they was returning that everything is ok and they are working.

**Comment by pongad** [comment]
@jkupcho The `Subscriber` was implemented using [Guava's Service](https://github.com/google/guava/wiki/ServiceExplained) so it is generally thread safe.

As explained in the linked page, there are some illegal actions though. You can't start service after it has stopped, etc. I'll add this documentation.

**Comment by pongad** [comment]
@Mistic92 Does your subscription usually have idle time where there's no message to consume? If so, it's likely you're running into the same problem. If you have root access to the machine, can you try running this command: `sudo /sbin/sysctl -w net.ipv4.tcp_keepalive_time=60 net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5`?

We hope to soon release a more permanent fix for this.

**Comment by Mistic92** [comment]
@pongad yep, currently we have only testers using backend so there is often time when no messages are send. I was supposing that's the reason. I'll try add this command to docker and see what's the result;)
