### ISSUE TITLE
How do I configure the firewall?

### ISSUE THREAD

**Issue by emilianbold** [GoogleCloudPlatform/google-cloud-java#2516]
Hello,

I can't seem to find a way of configuring any kind of firewall rules on an instance or project from Java.

I'm able to launch a machine with SSH but I would like to also control who gets to connect. 

The EC2 Java API has the authorizeSecurityGroupIngress method where I can define a CIDR, ports and protocols. I expect something similar from Google Compute Engine.

**Comment by anthmgoogle** [comment]
Can you provide more information? Are you trying to do this using the user interface, the Cloud SDK or programatically using google-cloud-java/google-cloud-compute.

Specifically google-cloud-compute is an Alpha-level library and will not comprehensively cover the API in its current form in the near future. 

If you need programatic control over Compute Engine instances, the current recommended solution is to use the commands in the Google Cloud SDK:
https://cloud.google.com/sdk/

**Comment by emilianbold** [comment]
I am using Google Cloud Client Library for Java, ie. this very project google-cloud-java, using the Maven dependencies.

Using the command line tools for a Java app doesn't really solve my issue. How to I distribute and install those? Do I just ask the user to have them already installed? Do I execute an external app for each request?

If some poor soul ends up on this issue, the workaround is to use the previous "maintentance mode" library https://github.com/google/google-api-java-client which does have `com.google.api.services.compute.model.Firewall`.

Of course, it's not great to have to pick between the 'old' and the 'alpha' library. I'm really amazed these are the options Google provides.

**Comment by anthmgoogle** [comment]
In your situation, the best option may be to https://github.com/google/google-api-java-client if the Cloud SDK is not a good target for programming against. While these libraries are not having much active development, they are supported and the code-generation will automatically be 100% in sync with the API.

We realize that the current situation where some google-cloud-<langugage> clients do not fully cover the API and many of them are missing is not good. We are actively working on code-generation solutions to cover Cloud APIs fully, but these solutions may not arrive fast enough for you.

This particular solution for Compute was an unfortunate case where someone started a manually written API for a case that was much better suited to code-generation. Compute has a huge amount of methods (~200) but does not need manual abstractions. We debated deleting this partly written manual client, but reasoned that it would be better to do that only when a more comprehensive generated solution was available, since some customers are successfully using this today.

Sorry we don't have a better option in the short term.

**Comment by emilianbold** [comment]
Right now I'm using google-cloud-java *and* google-api-java-client (for the firewall) which seems like a hack but... works. Really glad I'm finished with all this!

**Comment by anthmgoogle** [comment]
Yes, right now that may be the least worst way to use a set of APIs. Use google-cloud-java for APIs with Beta or GA clients because they will generally be better, and fall back to google-api-java-client for all others.

Obviously that is a bad story overall. We are working towards allowing you to use google-cloud-java for everything to get out of this.

**Comment by anthmgoogle** [comment]
Closing since we have settled on the recommendation for now. Please reopen or start a new issue if there is more we can help with.
