### ISSUE TITLE
Translate:  Invalid credential path in GOOGLE_APPLICATION_CREDENTIAL results in "The request is miss a valid API key." error

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-java#2535]
# Steps to reproduce:

1. Configure a Java project  with the cloud-translate Java library
```		
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-translate</artifactId>
	<version>1.6.0</version>
</dependency>
```
 or use [one I prepared earlier](https://github.com/patflynn/spring-boot-with-cloud-libraries).
1. Make sure your code makes a translate API call.
1. export GOOGLE_APPLICATION_CREDENTIALS='/a/no/good/path/to/nothing' as part of your project's run configuration.
1. Run your code.

# Observe in your logs:
```
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "errors": [
      {
        "message": "The request is missing a valid API key.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
]

```
# Expected result:
An exception identifying the invalid credential path as the cause of the error.

**Comment by andreamlin** [comment]
There are multiple ways to pass in credentials into the client, Setting the GOOGLE_APPLICATION_CREDENTIALS environment variable is one of the simplest ways to pass in credentials, but it's not the only way (see https://developers.google.com/identity/protocols/application-default-credentials). We can't immediately throw an exception if the GOOGLE_APPLICATION_CREDENTIALS is an invalid path or contains an invalid API key because the auth library will consult other variables for authentication.

Closing this issue for now. Feel free to reopen this if necessary!

**Comment by patflynn** [comment]
IMO if GOOGLE_APPLICATION_CREDENTIALS is set with a value that is incorrect, it should generate an error immediately.  If it's unset then you can fallback to other credential passing mechanisms.   As it is the error is extremely confusing and hard to debug.
