### ISSUE TITLE
Is google-cloud-java GCE misrepresented in root README

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#2732]
From b/70926158

In the README for GCE:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-compute/README.md

"Note: This client is no longer receiving updates; new features in the Compute API will not be added to this client. Check https://cloud.google.com/compute/docs/api/libraries for the recommended Java client library to use for accessing Compute."

Yet this is listed in the main README as having "alpha" support:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/README.md

"This client supports the following Google Cloud Platform services at an Alpha quality level:
- Cloud Compute (Alpha)"

This seems misleading, and that the GCE component should be in a separate section, or marked somehow at this level, especially since the following page points people to this component as the "preferred" client library, in general:

https://cloud.google.com/apis/docs/cloud-client-libraries

**Comment by garrettjonesgoogle** [comment]
I'm not really sure what to call a release level for a client that is no longer receiving updates - do we have precedent anywhere? It's potentially a different dimension from release level - for example, you could have a GA client that is no longer receiving updates. Even if we added some kind of note, "alpha" may still be appropriate.

As for misleading: Yes, google-cloud-java is the preferred client library in general, but the Cloud docs on compute don't point to it:

https://cloud.google.com/compute/docs/api/libraries

**Comment by pongad** [comment]
@garrettjonesgoogle Is there a concrete action to take here? I suppose we could put it under "deprecated" header?

**Comment by garrettjonesgoogle** [comment]
I think we should wait until the new generated client is out and we move the old code under a .deprecated java package; at that point we should create a new Deprecated header.

**Comment by dtretyakov** [comment]
As far as I understand GCE APIs from this project are deprecated in favor of https://mvnrepository.com/artifact/com.google.apis/google-api-services-compute

Is it true and where is a repository of the mentioned maven library?

@garrettjonesgoogle, you mentioned in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2686#issuecomment-360311659 that GCE API will be replaced by completely different "surface". But mentioned maven library was released in 2015, so I'm wondering what's going on in Google Cloud libraries because it was expected that current GCE APIs will be transition to Beta and then to GA.

Could you please create an announcement repository to be in touch with partners which could use your libraries in their products? Examples of such repositories:
* https://github.com/NuGet/Announcements
* https://github.com/dotnet/announcements

Currently unclear should we rewrite our code by using mentioned maven library or wait for unpredictable amount of time for some new libraries.
