### ISSUE TITLE
CloudStorageFileSystem: can not list content of root directory

### ISSUE THREAD

**Issue by bitkid** [GoogleCloudPlatform/google-cloud-java#2756]
```
CloudStorageFileSystem.forBucket("someBucket", CloudStorageConfiguration.builder().permitEmptyPathComponents(true).build()).use {
            println(Files.list(it.getPath(".")).toList().size) // prints 0 although there is a file in the bucket
        }
```
println(Files.list(it.getPath("/")).toList().size) throws an exception
java.lang.IllegalArgumentException: I/O not allowed on empty Google Cloud Storage object names.

**Comment by vam-google** [comment]
Hi @bitkid,

Can you please post a more comprehensive example (preferably in Java). 
According to the provided description: `it.getPath(".")` is used, but the exception is thrown for `it.getPath("/")` (different path, which is odd).

In any ways seems like a bug, since yes, an `IllegalArgumentException` will be thrown at [CloudStoragePath.java#L143](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java#L143), because `objectName.isEmpty() == true` since the only character  ("/") of the path will be truncated few lines before that at [CloudStoragePath.java#L139](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java#L139).

**Comment by hzyi-google** [comment]
#2809 fixes this.
