### ISSUE TITLE
Spanner: Add API for binding lists of tuples into queries

### ISSUE THREAD

**Issue by AgentME** [GoogleCloudPlatform/google-cloud-java#2759]
Spanner supports queries with lists of tuples: `SELECT * FROM Foo WHERE (a, b) IN (("x", 1), ("y", 2))`. The Spanner API library's Statement builder seems to not support any way of binding the tuple list dynamically into the query. As far as I can tell, there's no way to give it a string like `SELECT * FROM Foo WHERE (a, b) IN @var` and construct a query like the one above. (I imagine that value would be given as a List of Struct objects each with "a" and "b" properties.)

There's methods for binding various types of arrays (`Statement.newBuilder(...).bind(...).toStringArray(...).build()`), but no way to provide an array or list of Struct objects or equivalent.

Currently, it seems like I have to dynamically create the query string and escape the values into the string myself.

**Comment by vam-google** [comment]
Hi @AgentME,

To the best of my knowledge it is currently not implemented. Please check some (weak) reasoning below.

It looks like you are encountering a common nuisance for "querying" clients/apis. A similar issue exist in relational DBs world, where a prepared statement (a precompiled SQL statement) can have various number of scalar params (i.e `?` signs (or named `@vars`) in the query), but cannot have tuple params, so as in your example, `where (a, b) in (?)` would be invalid. Precompiling statements with tuple parameters is too difficult/impossible, that is why is usually not supported on server side.

In SQL world (and this essentially also applies to spanner), higher level libraries (like Hibernate) allow to construct queries with tuple params, but underneath it usually results to creating the query dynamically (i.e. string concatenation + escaping) and does not allow the DB to perform necessary optimizations for a repeatedly executed query (compared to prepared statement version), because it treats each query as a completely new one, instead of similar query with same template but different parameter values.

**Comment by AgentME** [comment]
Thanks for the response! I'm reassured to know I'm not committing too terrible of a sin by constructing the query string dynamically myself.

Does the spanner client library have any utility functions I should be making use of for escaping strings?

**Comment by vam-google** [comment]
To the best of my knowledge it does not. I'm not en expert on the Spanner client, but it seems the only thing which marginally facilitates dynamic query creation is `Statement.Builder.append(String)` method, which allows to append stuff to the query, but it does not escape but only checks for non-null. In other words escaping should be done manually.

@vkedia Please advice on what we can do here. Is there any chance that we can implement this feature in the future? If no then, I believe we will have to close this issue unresolved.

**Comment by adirastogi** [comment]
@AgentME  It's ugly but you can rewrite your query to join over array parameters for individual columns using the offset and then join it against the table, like so:
```
select * from Foo f join (
	select p.a, q.b from
	( select a, o_a from unnest(@a_array) as a with offset o_a ) p
	join
	( select b, o_b from unnest(@b_array) as b with offset o_b ) q
        on p.o_a = q.o_b ) 
) r on f.a = r.a and f.b = r.b 
```

**Comment by vkedia** [comment]
Thanks @adirastogi . Since this is a limitation of the underlying API and not really of the java library, I will close this issue.
