### ISSUE TITLE
it's very difficult to unit test with non-publicly-constructable data types

### ISSUE THREAD

**Issue by pmkc** [GoogleCloudPlatform/google-cloud-java#2769]
I am writing a small wrapper around google-cloud-bigquery that is illustrated by

```java
  public long getNumRows(BigQuery bq, String dataset, String table) {
    return bq.getTable(dataset, table)
        .<StandardTableDefinition>getDefinition()
        .getNumRows();
  }
```

When I go to unit test this method I have to mock out `Table` and `StandardTableDefinition`, because `Table` doesn't have a public builder and `StandardTableDefinition`'s public builder does not have a public `setNumRows`.

This less usable than the underlying generated library where I can construct all the model objects directly. I have had this issue with other google-cloud-java components as well.

I understand the desire to minimize the public API for maintainability, but some kind of testing visibility for constructing ADTs would help a lot.

**Comment by vam-google** [comment]
I agree that being able to construct model objects has value and it would make the google-cloud-java clients more usable and testable. 

For your particular case, I believe the problem is in the overall approach chosen for the manual portion of google-cloud-java clients (BigQuery is one of them). It uses "thick" objects, which not only represent model, but also encapsulate the actual client. I.e. when you want to do something with your table you do somethign like:

```java
table.update(options)
```
instead of 
```java
bigQueryService.updateTable(table, options)
```
Since table object is much more than just a set of table properties/data, it is much  harder (more dangerous) to expose its creation process, that is why it is hidden from surface.

The new clients and already existing autogenerted ones (`bigtable`, `dlp, all machine-learning clients (`speech`, `video-intelligence` and others) etc.) do not have this problem, they separate service and model objects, allowing you to instantiate them freely in your test code.

**Comment by pmkc** [comment]
I'm not sure how dangerous adding `@VisibleForTesting` and public to `Table.Builder`'s internal constructor, would be, but I understand it exposes implementation details of a thick object albeit one that just delegates to a `BigQuery` object.

Making all fields of the pure datatype `StandardTableDefinition.Builder` settable on the other hand, would not in anyway expose implementation details.
