### ISSUE TITLE
Consider Gradle build system

### ISSUE THREAD

**Issue by anthmgoogle** [GoogleCloudPlatform/google-cloud-java#286]
Maven is very popular and idiomatic as a build system for Java. Gradle is also becoming very popular for Java. Has there been any discussion among owners of the project about potentially moving to Gradle? 

Some reasons this might be interesting:
1. GRPC Java (https://github.com/grpc/grpc-java) uses it and there may be opportunity to leverage extensions for consuming gRPC components.
2. There is at least one significant performance difference in that "mvn install" can take minutes, while the Gradle equivalent takes less than 30 seconds.

**Comment by aozarov** [comment]
Personally I don't have much experience with gradle but I assume that maven is much more popular just because it is around for much longer.

Tools, and their quality, (e.g. IDE support) is also something that we should consider.

I don't think `mvn install` is a common thing to do with `gcloud-java`.

I do wonder how popular gradle is among GoogleCloudPlatform or Google github projects?
The ones I am familiar with appengine-xxxx projects, Guice, Guava are using maven.

I also wonder what would be the cost of the transition mainly in the deploy and site building.

/cc ludoch

**Comment by wrwg** [comment]
Yes, maven is more common today probably because it's much longer around. The Google projects you cite likely don't use it also because they pre-date its rise.

After working with Gradle now for a few weeks, I must say it is a very impressive system. It's very easy to use, and requires less boilerplate to setup things. Gradle becomes more complex only if customization is needed, but that is just because it can do so much more than other systems.

Gradle is used for all of Android. It is also used by grpc and protobuf.

For gcloud-java, it might be essential to use because of the grpc and protobuf dependency. If we would not use Gradle, then we would have to re-engineer the build logic around locating and automatically downloading right versions of protoc, proto runtime, and generating stubs from it, as well as the synchronization logic of generated and edited code which comes with the veneer toolkit.

I'm happy to create a PR a bit later which showcases how the migration would look like. I expect it's not being too complicated.

**Comment by wrwg** [comment]
PS. As you were asking for IDE support: it's working very with Gradle, both for Eclipse and IntelliJ.

**Comment by wrwg** [comment]
And for a last note, this is a good article about migration experience: https://julien.ponge.org/blog/an-experiment-in-maven-to-gradle-migration/

**Comment by mziccard** [comment]
I like Gradle better than maven. However I am not sure how much of a pain would be migrating from maven to gradle given our multi-module artifact deploy and site creation.

I couldn't find anything similar to `mvn site` and I know this has been a blocker for several open source projects for a while. https://github.com/breskeby/GradleSite is a very outdated wrapper, while https://bitbucket.org/davidmc24/gradle-site-plugin is another site-publish plugin but it seems to have no automatic site creation. If we move to gradle we might have to build our site by hand, which I am not against.

**Comment by aozarov** [comment]
@wrwg as for the "essential to use because of the grpc and protobuf dependency" part, it looks like
[grpc-java](https://github.com/grpc/grpc-java) provides both a maven artifact for the core library as well as a maven plugin for protobuf-based codegen. Is there more to it?

**Comment by wrwg** [comment]
Where did you find a maven plugin for generating Java code from proto? I only know about the [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin). There are some older maven plugins from others but they are not supported by the grpc team AFAICT.

Gradle produces maven artifacts for mavenCentral and mavenLocal as well as other package repositories. Did you mean this?

**Comment by aozarov** [comment]
@wrwg did you look at the [link](https://github.com/grpc/grpc-java) I mentioned?
It is described in the first page as such:

Download the JAR. Or for Maven, add to your pom.xml:
```
<dependency>
  <groupId>io.grpc</groupId>
  <artifactId>grpc-all</artifactId>
  <version>0.9.0</version>
</dependency>
```

...
For protobuf-based codegen integrated with the Maven build system, you can use [maven-protoc-plugin](http://sergei-ivanov.github.io/maven-protoc-plugin/):
...

**Comment by wrwg** [comment]
@aozarov Thanks for the pointer, I actually have not seen the link to the maven-protoc-plugin, as if you continue to read the grpc repo, its all based on protobuf-gradle-plugin ;-)

**Comment by garrettjonesgoogle** [comment]
I am going to close this now - we don't have imminent plans to move to Gradle.
