### ISSUE TITLE
BigQuery: Job already exists, probably for internal backoff or something

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-java#2867]
Hi, 
I'm currently using library 0.33.0-beta for an App Engine Std project,

When I need to execute a QueryJob, I have this method
```
public static TableResult executeQuery(QueryJobConfiguration queryConfig) throws IOException {
	BigQuery service = getService();

	JobId jobId = JobId.of(UUID.randomUUID().toString() + "-" + System.nanoTime());
	Job queryJob = service.create(JobInfo.newBuilder(queryConfig).setJobId(jobId).build());

	// Wait for job to finish
	queryJob = job.waitFor(retryOption);

	// Get the results
	TableResult result = queryJob.getQueryResults();
	
	// TODO Do something with the results...
}
```

You can see from the code itself the JobID is unique, due it has a random part and a time part.

But sometimes I get this error:
```
{
  "code": 409,
  "errors": [
    {
      "domain": "global",
      "message": "Already Exists: Job xxxxxxxxxxxxxxxx:EU.80760581-e8df-4c87-a538-1efbcf917778-1517936402050522782",
      "reason": "duplicate"
    }
  ],
  "message": "Already Exists: Job  xxxxxxxxxxxxxxxx:EU.80760581-e8df-4c87-a538-1efbcf917778-1517936402050522782"
}
```

and here is the stacktrace
```
com.google.cloud.bigquery.BigQueryException: Already Exists: Job xxxxxxxxxxxxxxxx:EU.80760581-e8df-4c87-a538-1efbcf917778-1517936402050522782
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:83)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:167)
	at com.google.cloud.bigquery.BigQueryImpl$3.call(BigQueryImpl.java:186)
	at com.google.cloud.bigquery.BigQueryImpl$3.call(BigQueryImpl.java:183)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:183)
	--- my class ---
```

Because I'm sure that my code generates every time a random/unique JobId (even if i Try multiple times the same query the id will be different) I'm wondering the conditions on how this kind of error is genereated.

I'm open this issue because I'm thinking about an internal backoff functionality (I can see the method **runWithRetries** from the stacktrace, this is why i'm suggesting this), where the jobs.create call ends w/o response (so the backoff try again to run the job) but the job successfully started the first time. In this way, trying to start a new job (same id) a second time, will produce this error.

It does not happens very often, so probably are temporary errors related to BigQuery infrastructure (and because of this is hard to replicate behaviour).

Is this a known behaviour?

**Comment by pongad** [comment]
@NicolaSpreafico I believe you're understanding this right.

@tswast I vaguely remember us talking about this. I *think* the recommendation is that users can catch this error can call `bigquery.getJob(jobId)` right? I must admit the "already exists" code is a little mysterious. Should we continue to retry `create`? I'll assign this to you to confirm, but please assign it to me if we need code change.

**Comment by tswast** [comment]
Yeah, probably has to do with retry logic. The trouble is that we don't know if the "already exists" is because someone else has created the job or if it was us and our previous create request just had a hiccup.

If the client library has generated the ID, I suppose we have a pretty good idea that it was the latter (just a hiccup), but we can't know this is the case when the user supplies it.

**Comment by tswast** [comment]
To summarize the action items here:
- @NicolaSpreafico since you are generating your own job ID, there's not much the client library can do to help in this case. You'll need to catch the "already exists" errors and call get yourself.
- We should document this failure case and the workaround of calling get()
- In the case where the job ID is generated by the client library we can catch this error and call get() ourselves. (We could potentially always do this, but that would give incorrect / surprising behavior in case when we are supplied a Job ID that is not unique.)

**Comment by pongad** [comment]
@tswast I agree with documentation. I started to look into automatically call `get()`; we have a few options.

1. Keep current behavior; user catches exception and call `get()`
    * Understandably annoying.
2. Hard-code `query(QueryJobConfiguration)` to catch and call `get()`
    * This will help some users but won't solve this specific problem, since @NicolaSpreafico used `create`, not `query`. Also won't help copy/load jobs, etc.

The `JobId` is a part of an object sent to `create`, so `create` itself doesn't know whether the ID is randomly generated or not.

3. We can make `JobId` remember whether it has been randomly generated, by adding field `boolean random`, that's only set to true if constructed by `JobId.of()`. This raises another question, should `random` take part in `hashCode` and `equals`?
    3a. It does. This is a breaking change as now given
```java
JobId a = something();
JobId b = JobId.of(a.getProject(), a.getJob());
```
, `a` no longer equals `b`. Similarly, given
```java
JobInfo info = something();
Job job = bigquery.create(info);
```
The `JobId` of `info` and `job` might be different. `info.jobId.random` is true if it was randomly generated by the client. `job.jobId.random` is always false; the client can never prove that it was randomly created.
    3b. It doesn't, but now we have two objects that compare equal except they behave differently in obscure ways. To future users, it might make failures harder to track down.

I think we're choosing between bad choices. Do you have an opinion?

**Comment by tswast** [comment]
(1) Annoying for sure. Feels like a failure on our part, since even though we have a handwritten library, with automatic retries, we don't handle a known failure case for them.

(2) Won't work, because the same problem applies to other kinds of jobs: load, copy, extract.

(3) I don't like having a `random` field of JobId, either. Both options feel bad, though making `random` not affect `equals` or `hashCode` is less bad.

(4) Why do we require a `JobId` to use `create`? Couldn't there be a way to create a job but let the client library deal with `JobId`?

**Comment by pongad** [comment]
@tswast You're right about (4). I misread the current implementation. Sent out a PR to fix this.
