### ISSUE TITLE
External user feedback regarding the GCS Download Object sample

### ISSUE THREAD

**Issue by starsandskies** [GoogleCloudPlatform/google-cloud-java#2899]
This feedback came to the GCS Docs as bug 68217327.

The feedback applies to the Java sample for downloading objects from GCS, found at https://cloud.google.com/storage/docs/object-basics#download

The body of the feedback was:
"The example to download an object already has a populated blobId. What is a blobId? How do I make one?"

I believe they're referring to the fact that the download sample takes a BlobId parameter and assumes that users of the sample will know what a BlobId is.

**Comment by pongad** [comment]
Makes sense. We should probably show `BlobId id = BlobId.of(bucketName, objectName)`. @hzyi-google can you take this on?

**Comment by hzyi-google** [comment]
This doesn't look like an easy fix but please correct me if I am wrong. 

The examples actually work in command line like this: `DownloadAction` extends `StorageAction<Tuple<BlobId, Path>>`, and when running from command line, `DownloadAction` will first call `parse(String... args)` to parse command line arguments into an instance of `Tuple<BlobId, Path>`,  and then call `public void run(Storage storage, Tuple<BlobId, Path> tuple)` using the parsed tuple which in turn calls the private method `run` to actually work on downloading. Therefore, Changing the signature of `private void run(Storage storage, BlobId blobId, Path downloadTo)` to `private void run(Storage storage, String bucketName, String objectName, Path downloadTo)` will break the whole structure. 

I am not exactly sure why `Tuple` is used here (and used for all the actions) since a tuple can only take two elements. A workaround might be making `DownloadAction` extend `StorageAction<Tuple<Tuple<String, String>, Path>`. Any thoughts? @pongad

**Comment by pongad** [comment]
Correct me if I'm wrong. The `DownloadAction.run` itself isn't in the example. So we can make the first `run` extract the project and object IDs from `BlobId`, then pass them on to the second right?

**Comment by hzyi-google** [comment]
Yes, that should work. Working on it.
