### ISSUE TITLE
DatastoreReader missing method overloads with the ReadOption parameter

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/google-cloud-java#2901]
`Datastore` has `Entity get(Key key, ReadOption... options);` but this method is missing from the `DatastoreReader` interface.

**Comment by pongad** [comment]
@wsh Correct me if I'm wrong. IIUC, `DatastoreReader` is purposefully missing the `ReadOption` since the reader can be used in contexts where the options don't make sense, like in a transaction?

**Comment by wsh** [comment]
:/ Honestly, I don't know. What you've said makes sense given that `Transaction` implements `DatastoreReader` (and the only `ReadOption` defined is for eventual consistency, which wouldn't make sense in that context as you note), but I wasn't around for its design so I can't say for certain that its omission was intentional. @lesv? @jabubake?

**Comment by pongad** [comment]
What I got out of it: `ReadOption` can be used to tweak the read consistency. In transactions, it's not useful for a read to be eventually consistent. I might be missing something though.

**Comment by stickfigure** [comment]
Presumably it was named the generic-sounding ReadOption because there might be other options in the future, which may or may not apply within transactions?

**Comment by jabubake** [comment]
@wsh @pongad  I don't know either, but it does seem like poor naming by assuming that all ReadOptions (current /future ) are not transaction safe.

**Comment by pongad** [comment]
I agree that the name is rather poor. Unfortunately, we can't change the name without breaking users now.

I motion that we close this for now. If we need the consistency option, it's possible to either use `Datastore` instead of `DatastoreReader` or do something like
```
DatastoreReader reader = ...
if (reader instanceof Datastore) {
  ((Datastore) reader).get(key, option);
} else {
  reader.get(key);
}
```
if we need the consistency option when out of transactions.

This is something we should revisit if/when we add more `ReadOption`s though. Then, we'll have more concrete data to design with.

**Comment by pongad** [comment]
From lack of objection, I'll close this for now. Please reopen if there's an action item we should tackle.
