### ISSUE TITLE
Method listing the contents of a bucket in FakeStorageRpc does not use bucket name

### ISSUE THREAD

**Issue by norbjd** [GoogleCloudPlatform/google-cloud-java#2902]
Hello,

The implementation of the method `list(String bucket, Map<Option, ?> options)` in `FakeStorageRpc` does not use `bucket` parameter to retrieve the files inside the bucket passed as parameter (see [FakeStorageRpc.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.34.0/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java#L122)). I'm using version 0.34.0, but it seems like in previous versions the behaviour was similar. Am I missing something ?

As a consequence, when using `LocalStorageHelper` (using `FakeStorageRpc`) for local testing purposes, the following code does not retrieve only the files in the bucket passed as parameter, but all files in all created buckets : 

```
Storage storage = LocalStorageHelper.customOptions(true).getService()

[...] // creating dummy files in two separate buckets (b1 and b2)

storage.list("b1") // returns all files in b1 and b2
```

I double checked in the doc, listing the contents of a bucket is however [defined as a supported operation](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.34.0/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java#L53).

**Comment by hzyi-google** [comment]
Hi @norbjd ,

I believe the behavior is on purpose but the documentation does indeed cause confusion.

This class is used to help test `CloudStorageFileSystem`. The [cloud storage file system](https://cloud.google.com/storage/docs/gcs-fuse) has similar behaviors as a file system whose root directory is a bucket. In this sense, it become much less important for the `FakeStorageRpc` class to support functionality across multi buckets. Also, the fact that `FakeStorageRpc` does not support creating, getting, deleting and listing of buckets should be due to the same reason.

If you do want to add testings to `storage` itself locally, unit tests in `google-cloud-storage` using mocks might be helpful.

@pongad Please take a look and see if I am correct. That being the case, shall we adjust the documentation?

**Comment by pongad** [comment]
I believe @hzyi-google is right (I'm not super familiar with this class myself). The `FakeStorageRpc` behaves as if it is bound to one bucket.

We should definitely document this. We can treat the ability to properly handle buckets as a feature request.

**Comment by norbjd** [comment]
Thanks for your replies @hzyi-google @pongad 

It's all clear now, in fact I was just confused because the `bucket` parameter is not used in the implementation of `list` method in `FakeStorageRpc`.

I looked to tests in `google-cloud-storage` as you suggest ([BucketTest.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java#L232)), but I am not able to used these tests "as-is", since many classes are package-private (for instance, I can't initialize a `Blob`).

`Storage` can be mocked, and in this example, mocking also `Blob` works, but I still think it will be a good idea to implement method to test storage locally (with `LocalStorageHelper`) without any mocking.

**Comment by hzyi-google** [comment]
I believe you are right. Let's treat this as a feature request.

**Comment by hzyi-google** [comment]
The feature request is added to the backlog. Feel free to add comments here.
