### ISSUE TITLE
Create API for GCE Metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-java#302]
There's a great metadata service for getting access to information on the VM. It would be great to have a structured API for this:
https://cloud.google.com/compute/docs/metadata?hl=en

**Comment by mziccard** [comment]
That would be nice indeed. I think we will investigate this as part of #85.
The only "issue" I see is that gcloud-java is meant to provide access to Google Cloud services from everywhere while the GCE metadata API is only available from inside a GCE VM, right? 
But we can always add this support and document it's only available from a GCE VM (throws exception otherwise). How does this sound?

**Comment by dtretyakov** [comment]
It would be great to have such API to get rid of manual metadata retrieving and don't forget to support "wait-for-change" feature.

**Comment by garrettjonesgoogle** [comment]
Requests for new clients are being tracked internally. Closing out this issue.
