### ISSUE TITLE
Batch acknowledgement is not working in asynchronous call

### ISSUE THREAD

**Issue by anamika-papajohns** [GoogleCloudPlatform/google-cloud-java#3257]
We are having the requirement of creating a batch of messages on every one minute. 
Once batch is processed and return success in response, we need to acknowledge all the messages which were present in that batch.
If batch process response is failure , we need to unacknowledged the messages.

Current functionality given by pub/sub library: In asynchronous call, we can ack/nack message one by one, immediate after receiving.

Below is our code snippet-
```java
Subscriber.Builder builder = Subscriber.newBuilder(subscription, new MessageReceiver() {
                @Override
                public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
                    // handle incoming message, then ack/nack the received message
              try {                             
                       //dropping the message in a queue
                      //here we are creating a batch on every one minute and ack/nack the message accordingly
                                
                     }
```
also do we have any method to get ackId instead of MessageId in case of asynchronous call.

**Comment by pongad** [comment]
@anamika-papajohns Let's see if I understand this right:

You want to pull many messages, process all of them, and either ack or nack all messages you pulled, is this right?

I don't think this use case is well-supported by pubsub. The reason is that pubsub guarantees "at least 1 delivery". If you ack 10 messages, sometimes some of the acks will be lost and some messages will get redelivered.

Is it possible to, for example, pack "sub-messages" into one pubsub message?

**Comment by hzyi-google** [comment]
It seems the problem is solved here. Please ask for reopening if not.
